default: &default
  adapter: postgresql
  host: localhost
  username: zavala
  password: <%= Rails.application.credentials.database.password %>
  database: zavala_club
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  primary:
    <<: *default
  cache:
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
