default: &default
  adapter: postgresql
  host: localhost
  username: zavala
  password: <%= Rails.application.credentials.database.password %>
  database: zavala_club
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
